name: Build and Deploy UI

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build UI
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy build files to the server
        run: |
          scp -r ./dist/* root@64.226.124.91:/var/www/tripwiz.me/html/
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}

      - name: SSH to Server and Restart Nginx
        run: |
          sshpass -e ssh root@64.226.124.91 "sudo systemctl restart nginx"
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
