name: Build and Deploy UI

on:
  push:
    branches:
      - prod # Change to the branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install # Use npm or yarn, depending on your project

      - name: Build UI
        run: npm run build # Adjust the build command as needed

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh root@64.226.124.91 "sudo systemctl restart nginx"
